
name = "join-room-worker"
main = "src/index.ts"
compatibility_date = "2024-07-11"

[[kv_namespaces]]
binding = "ROOM_KV"
id = "f248bd25988f4935bf26c3ae2591daf1"

[env.preview]
[[env.preview.kv_namespaces]]
binding = "ROOM_KV"
id = "19d75d7b17d84091b51f8b02c2953119"  # ← Preview ID from your output

dev = { port = 8787 }
routes = [
  "https://skribbl-clone.com/api/rooms/join" 
]