name: CI - Backend Check

on:
  push:
    paths:
      - 'apps/backend/**'
    branches:
      - main
  pull_request:
    paths:
      - 'apps/backend/**'

jobs:
  backend-ci:
    name: Type Check Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0

      - name: Install dependencies
        run: npm install

      - name: Type-check backend
        run: npm run build:backend
